global:
  storageClass: ""
  nodeSelector: {}
  affinity: {}
  tolerations: {}
replicaCount: 1
metadata:
  labels:
    environment: dev
image:
  repository: naleli1011
  name: sakai
  tag: latest
  # image: naleli1011/sakai:latest
  pullPolicy: ifNotPresent
service:
  type: ClusterIP
  port: 8080
  jmxport: 8280
secrets:
  username: sakai
  password: examplepassword
resources: {}
  # requests:
  #   cpu: 10m  # Request 100 millicpu (0.1 cpu)
  #   memory: 28Mi  # Request 128 MiB of memory
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes:
    sakaidbdata:
      capacity: "4Gi"
      claimName: "sakaidbdata-pvc"
nodeSelector: {}
affinity: {}
tolerations: {}
