apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: sakaidbdata-pvc
  name: sakaidbdata-pvc
spec:
  storageClassName: sakai-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sakaidbdata-pv
spec:
  storageClassName: sakai-storage-class
  claimRef:
    name: sakaidbdata-pvc
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/sakai/sakaidbdata'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sakaidb
    environment: local
  name: sakaidb
spec:
  selector:
    matchLabels:
      app: sakai
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sakai
        environment: local
    spec:
      containers:
        # - args:
        #   - --character-set-server=utf8
        #   - --collation-server=utf8_general_ci
        #   env:
        #   - name: MYSQL_DATABASE
        #     value: sakai
        #   - name: MYSQL_PASSWORD
        #     value: examplepassword
        #   - name: MYSQL_ROOT_PASSWORD
        #     value: examplerootpassword
        #   - name: MYSQL_USER
        #     value: sakai

          image: naleli1011/mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: sakaidbdata
      restartPolicy: Always
      volumes:
        - name: sakaidbdata
          persistentVolumeClaim:
            claimName: sakaidbdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: '3306'
      port: 3306
      targetPort: 3306
  selector:
    app: sakai
    environment: local
  type: ClusterIP
