apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sakai-storage-class
  labels:
        app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: sakai-local
    meta.helm.sh/release-namespace: default
provisioner: microk8s.io/hostpath
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
